name: Build and push latest

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'main.go'

jobs:
  compile:
    runs-on: ubuntu-20.04
    outputs:
      new_version: ${{ steps.bump_semver.outputs.new_version }}
    name: Build and push docker image
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Login to OTC SWR registry
        if: success()
        uses: docker/login-action@v1
        with:
          registry: swr.eu-de.otc.t-systems.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: swr.eu-de.otc.t-systems.com/images/argocd-vs-fluxcd-application:1.${{ github.run_number }}
